# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-17 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('Sign', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=60)),
                ('chats', models.CharField(max_length=60)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Advise',
            },
        ),
        migrations.CreateModel(
            name='Arriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('std_name', models.CharField(max_length=60, unique=True)),
                ('chats', models.CharField(max_length=60)),
                ('qiandao_datetime', models.DateTimeField()),
                ('is_late', models.BooleanField()),
                ('late_reason', models.TextField()),
            ],
            options={
                'db_table': 'Arriver',
            },
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('advise', models.CharField(max_length=128)),
                ('Teacher', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'Chats',
            },
        ),
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=60)),
                ('time', models.DateTimeField()),
                ('chats', models.ManyToManyField(to='main.Chats')),
            ],
            options={
                'db_table': 'Msg',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, unique=True)),
                ('passwd', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('std_id', models.BigIntegerField()),
                ('img', models.ImageField(default='/collected_static/images/user.png', upload_to='/collected_static/images/')),
                ('chats', models.ManyToManyField(to='main.Chats')),
            ],
            options={
                'db_table': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, unique=True)),
                ('passwd', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('img', models.ImageField(default='/collected_static/images/user.png', upload_to='/collected_static/images/')),
                ('chats', models.ManyToManyField(to='main.Chats')),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
        migrations.AddField(
            model_name='msg',
            name='students',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Students'),
        ),
    ]
